// <auto-generated />
namespace FinalWindow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ntt5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ntt5));
        
        string IMigrationMetadata.Id
        {
            get { return "202305170742306_ntt5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
